//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class veritabani3Entities : DbContext
    {
        public veritabani3Entities()
            : base("name=veritabani3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<OdemeBilgileri> OdemeBilgileri { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunOzellikleri> UrunOzellikleri { get; set; }
        public virtual DbSet<UrunResimleri> UrunResimleri { get; set; }
        public virtual DbSet<UrunSepet> UrunSepet { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
        public virtual DbSet<RAPORLA> RAPORLA { get; set; }
    
        [DbFunction("veritabani3Entities", "Urunleri_getir")]
        public virtual IQueryable<Urunleri_getir_Result> Urunleri_getir(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Urunleri_getir_Result>("[veritabani3Entities].[Urunleri_getir](@param1)", param1Parameter);
        }
    
        public virtual ObjectResult<string> SP_RAPORLA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_RAPORLA");
        }
    }
}
