//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisID { get; set; }
        public int SepetID { get; set; }
        public decimal ToplamTutar { get; set; }
    
        public virtual Sepet Sepet { get; set; }
    }
}
